data<- file("household_power_consumption.txt", "r")
cat(grep("(^Date)|(^[1|2]/2/2007)",readLines(data), value=TRUE), sep="\n", file="selected.txt")
close(data)
DT<-read.table('selected.txt', sep=";", header=TRUE)
DT$Time<-strptime(paste(DT$Date, DT$Time), format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2), mar=c(4,4,2,2))
with(DT,{
  plot(Time, Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
  plot(Time, Voltage, type="l", xlab="datetime", ylab="Voltage")
  plot(DT$Time, DT$Sub_metering_1, type="n", xlab="", ylab="Energy Sub Metering")
  points(DT$Time, DT$Sub_metering_1, type="l")
  points(DT$Time, DT$Sub_metering_2, type="l", col="red")
  points(DT$Time, DT$Sub_metering_3, type="l", col="blue")
  legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(Time, Global_reactive_power, type="l", xlab="datetime", ylab="Global Reactive Power")
})
dev.copy(png, file="plot4.png")
dev.off()