data<- file("household_power_consumption.txt", "r")
cat(grep("(^Date)|(^[1|2]/2/2007)",readLines(data), value=TRUE), sep="\n", file="selected.txt")
close(data)
DT<-read.table('selected.txt', sep=";", header=TRUE)
DT$Time<-strptime(paste(DT$Date, DT$Time), format="%d/%m/%Y %H:%M:%S")
plot(DT$Time, DT$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
points(DT$Time, DT$Sub_metering_1, type="l")
points(DT$Time, DT$Sub_metering_2, type="l", col="red")
points(DT$Time, DT$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png, file="plot3.png")
dev.off()